

[tool.poetry]
name = "botaffiumeiro"
version = "1.0"
description = "Telegram bot for modifying links with affiliate programs"
authors = [
  "Héctor Martínez",
  "Daniel Martín"
]
license = "GPL3"
readme = "README.md"
repository = "https://github.com/hectorzin/botaffiumeiro"

[tool.poetry.dependencies]
python = ">=3.11,<3.14"

[tool.poetry.group.dev.dependencies]
pre-commit = "3.6.2"
pre-commit-hooks = "4.5.0"
pylint = "3.1.0"
ruff = "0.3.4"
mypy = "1.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
src = ["botaffiumeiro"]

[tool.ruff.lint]
ignore = [
  "ANN101", # Self... explanatory
  "ANN401", # Opiniated warning on disallowing dynamically typed expressions
  "D203", # Conflicts with other rules
  "D213", # Conflicts with other rules
  "TID252", # Relative imports
  "RUF012", # Just broken

  # Formatter conflicts
  "COM812",
  "COM819",
  "D206",
  "E501",
  "ISC001",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "W191",
]
select = ["ALL"]

[tool.ruff.lint.flake8-import-conventions.extend-aliases]
"telegram.ext" = "tgext"
"telegram" = "tg"
"handlers" = "h"
"config" = "cfg"

[tool.ruff.lint.isort]
force-sort-within-sections = true
known-first-party = [
    "botaffiumeiro",
]
combine-as-imports = true

[tool.pylint."MESSAGES CONTROL"]
# Reasons disabled:
# format - handled by ruff
# duplicate-code - unavoidable
# used-before-assignment - false positives with TYPE_CHECKING structures
disable = [
  "abstract-method",
  "duplicate-code",
  "format",
  "unexpected-keyword-arg",
  "used-before-assignment",
]

[tool.isort]
profile = "black"
combine_as_imports = true
known_first_party = ["botaffiumeiro"]
force_sort_within_sections = true
