name: Run Pre-Commit Checks

on:
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit types-requests types-PyYAML
          pre-commit install-hooks

      - name: Set up Pre-Commit
        run: bash setup_precommit.sh
            
      - name: Run Pre-Commit
        run: pre-commit run --all-files
